# install WCF basic docker image
FROM mcr.microsoft.com/dotnet/framework/wcf:4.8

# Create a directory on the container
RUN mkdir C:\Service

# Copy to cointainer
COPY Published "C:\\Service"

# run IIS
RUN powershell -NoProfile -Command \
Import-module IISAdministration; \
New-IISSite -Name "Service" -PhysicalPath C:\Service -BindingInformation "*:83:"

# This instruction tells the container to listen on port 83.
EXPOSE 83
