//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Calculator.LocalCalculator {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LocalCalculator.CalculatorSoap")]
    public interface CalculatorSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Addition", ReplyAction="*")]
        int Addition(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Addition", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AdditionAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Subtraction", ReplyAction="*")]
        int Subtraction(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Subtraction", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SubtractionAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplication", ReplyAction="*")]
        int Multiplication(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplication", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MultiplicationAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division", ReplyAction="*")]
        int Division(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DivisionAsync(int x, int y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculatorSoapChannel : Web_Calculator.LocalCalculator.CalculatorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorSoapClient : System.ServiceModel.ClientBase<Web_Calculator.LocalCalculator.CalculatorSoap>, Web_Calculator.LocalCalculator.CalculatorSoap {
        
        public CalculatorSoapClient() {
        }
        
        public CalculatorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Addition(int x, int y) {
            return base.Channel.Addition(x, y);
        }
        
        public System.Threading.Tasks.Task<int> AdditionAsync(int x, int y) {
            return base.Channel.AdditionAsync(x, y);
        }
        
        public int Subtraction(int x, int y) {
            return base.Channel.Subtraction(x, y);
        }
        
        public System.Threading.Tasks.Task<int> SubtractionAsync(int x, int y) {
            return base.Channel.SubtractionAsync(x, y);
        }
        
        public int Multiplication(int x, int y) {
            return base.Channel.Multiplication(x, y);
        }
        
        public System.Threading.Tasks.Task<int> MultiplicationAsync(int x, int y) {
            return base.Channel.MultiplicationAsync(x, y);
        }
        
        public int Division(int x, int y) {
            return base.Channel.Division(x, y);
        }
        
        public System.Threading.Tasks.Task<int> DivisionAsync(int x, int y) {
            return base.Channel.DivisionAsync(x, y);
        }
    }
}
